"""Tests for internal report management tools"""

import pytest
import json
import tempfile
from pathlib import Path
from ai_assist.report_tools import ReportTools


@pytest.fixture
def temp_reports():
    """Create a temporary directory for reports"""
    with tempfile.TemporaryDirectory() as tmpdir:
        yield Path(tmpdir)


@pytest.fixture
def report_tools(temp_reports):
    """Create ReportTools instance with temp directory"""
    return ReportTools(reports_dir=temp_reports)


class TestReportTools:
    """Tests for ReportTools class"""

    def test_initialization(self, report_tools, temp_reports):
        """Test that ReportTools initializes correctly"""
        assert report_tools.reports_dir == temp_reports
        assert temp_reports.exists()

    def test_tilde_expansion_in_env_var(self, monkeypatch, tmp_path):
        """Test that tilde in AI_ASSIST_REPORTS_DIR is properly expanded"""
        import os
        # Set env var with tilde
        test_dir = tmp_path / "test-reports"
        monkeypatch.setenv("AI_ASSIST_REPORTS_DIR", f"~/{test_dir.name}")

        # Create ReportTools - it should expand the tilde
        rt = ReportTools()

        # Path should be absolute and not contain literal ~
        assert rt.reports_dir.is_absolute()
        assert '~' not in str(rt.reports_dir)
        # Should have expanded to home directory
        assert str(rt.reports_dir).startswith(str(Path.home()))

    def test_get_tool_definitions(self, report_tools):
        """Test that tool definitions are returned"""
        tools = report_tools.get_tool_definitions()
        assert len(tools) == 5
        assert all(tool["_server"] == "internal" for tool in tools)

        tool_names = [tool["name"] for tool in tools]
        assert "internal__write_report" in tool_names
        assert "internal__append_to_report" in tool_names
        assert "internal__read_report" in tool_names
        assert "internal__list_reports" in tool_names
        assert "internal__delete_report" in tool_names


class TestWriteReport:
    """Tests for write_report functionality"""

    @pytest.mark.asyncio
    async def test_write_report_creates_file(self, report_tools, temp_reports):
        """Test that write_report creates a markdown file"""
        result = await report_tools.execute_tool(
            "write_report",
            {"name": "test-report", "content": "# Test Report\n\nContent here."}
        )

        assert "test-report" in result
        assert "written to" in result

        # Verify file exists
        report_file = temp_reports / "test-report.md"
        assert report_file.exists()

        # Verify content
        content = report_file.read_text()
        assert "# Test Report" in content
        assert "Content here." in content

    @pytest.mark.asyncio
    async def test_write_report_includes_timestamp(self, report_tools, temp_reports):
        """Test that write_report adds timestamp metadata"""
        await report_tools.execute_tool(
            "write_report",
            {"name": "timestamped", "content": "# Report"}
        )

        report_file = temp_reports / "timestamped.md"
        content = report_file.read_text()

        # Check for timestamp comment
        assert "<!-- Generated by AI Assistant on" in content
        assert "20" in content  # Year should be in 2000s

    @pytest.mark.asyncio
    async def test_write_report_overwrites_existing(self, report_tools, temp_reports):
        """Test that write_report overwrites existing files"""
        # Create initial report
        await report_tools.execute_tool(
            "write_report",
            {"name": "overwrite-test", "content": "# Original Content"}
        )

        # Overwrite with new content
        await report_tools.execute_tool(
            "write_report",
            {"name": "overwrite-test", "content": "# New Content"}
        )

        report_file = temp_reports / "overwrite-test.md"
        content = report_file.read_text()

        # Should have new content, not original
        assert "# New Content" in content
        assert "# Original Content" not in content


class TestAppendToReport:
    """Tests for append_to_report functionality"""

    @pytest.mark.asyncio
    async def test_append_to_existing_report(self, report_tools, temp_reports):
        """Test appending to an existing report"""
        # Create initial report
        await report_tools.execute_tool(
            "write_report",
            {"name": "append-test", "content": "# Initial Content"}
        )

        # Append to it
        result = await report_tools.execute_tool(
            "append_to_report",
            {"name": "append-test", "content": "Additional content"}
        )

        assert "Content appended" in result

        report_file = temp_reports / "append-test.md"
        content = report_file.read_text()

        assert "# Initial Content" in content
        assert "Additional content" in content

    @pytest.mark.asyncio
    async def test_append_with_section_header(self, report_tools, temp_reports):
        """Test appending with a section header"""
        await report_tools.execute_tool(
            "write_report",
            {"name": "sections", "content": "# Report"}
        )

        await report_tools.execute_tool(
            "append_to_report",
            {
                "name": "sections",
                "content": "Section content",
                "section": "New Section"
            }
        )

        report_file = temp_reports / "sections.md"
        content = report_file.read_text()

        assert "## New Section" in content
        assert "Section content" in content

    @pytest.mark.asyncio
    async def test_append_creates_file_if_not_exists(self, report_tools, temp_reports):
        """Test that append creates file if it doesn't exist"""
        result = await report_tools.execute_tool(
            "append_to_report",
            {"name": "new-report", "content": "First content"}
        )

        assert "Content appended" in result

        report_file = temp_reports / "new-report.md"
        assert report_file.exists()
        content = report_file.read_text()
        assert "First content" in content


class TestReadReport:
    """Tests for read_report functionality"""

    @pytest.mark.asyncio
    async def test_read_existing_report(self, report_tools, temp_reports):
        """Test reading an existing report"""
        await report_tools.execute_tool(
            "write_report",
            {"name": "readable", "content": "# Readable Report"}
        )

        result = await report_tools.execute_tool(
            "read_report",
            {"name": "readable"}
        )

        assert "# Readable Report" in result

    @pytest.mark.asyncio
    async def test_read_nonexistent_report(self, report_tools):
        """Test reading a non-existent report"""
        result = await report_tools.execute_tool(
            "read_report",
            {"name": "nonexistent"}
        )

        assert "not found" in result


class TestListReports:
    """Tests for list_reports functionality"""

    @pytest.mark.asyncio
    async def test_list_reports_empty_directory(self, report_tools):
        """Test listing reports in empty directory"""
        result = await report_tools.execute_tool("list_reports", {})

        reports = json.loads(result)
        assert isinstance(reports, list)
        assert len(reports) == 0

    @pytest.mark.asyncio
    async def test_list_reports_with_files(self, report_tools):
        """Test listing reports with files"""
        await report_tools.execute_tool(
            "write_report",
            {"name": "report1", "content": "Content 1"}
        )
        await report_tools.execute_tool(
            "write_report",
            {"name": "report2", "content": "Content 2"}
        )

        result = await report_tools.execute_tool("list_reports", {})

        reports = json.loads(result)
        assert len(reports) == 2

        # Check metadata
        assert all("name" in r for r in reports)
        assert all("size" in r for r in reports)
        assert all("modified" in r for r in reports)

        names = [r["name"] for r in reports]
        assert "report1" in names
        assert "report2" in names


class TestDeleteReport:
    """Tests for delete_report functionality"""

    @pytest.mark.asyncio
    async def test_delete_existing_report(self, report_tools, temp_reports):
        """Test deleting an existing report"""
        await report_tools.execute_tool(
            "write_report",
            {"name": "deleteme", "content": "Content"}
        )

        report_file = temp_reports / "deleteme.md"
        assert report_file.exists()

        result = await report_tools.execute_tool(
            "delete_report",
            {"name": "deleteme"}
        )

        assert "deleted" in result
        assert not report_file.exists()

    @pytest.mark.asyncio
    async def test_delete_nonexistent_report(self, report_tools):
        """Test deleting a non-existent report"""
        result = await report_tools.execute_tool(
            "delete_report",
            {"name": "nonexistent"}
        )

        assert "not found" in result
